### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [pangbo-1988/data_diff#1]
Hello,

is it possible that you can add a License file for your tool? Any License will suffice.

Thanks

**Comment by pangbo-1988** [comment]
Just add a new License. Thank you very much.

**Comment by xorond** [comment]
Thanks for the license, I was thinking of adding your tool into the ArchStrike repositories, but the tool name isn't very obvious to figure out. Should it be called data_diff or delta?

**Comment by pangbo-1988** [comment]
Thanks for using our tool. We use delta as the name. 

Also we are working on adding more features ( such as more input format ) to the tool, feel free to tell us if you need more functionality or find any issue.

Thanks a lot.

**Comment by xorond** [comment]
Alright thanks, will be adding in the repository as soon as I can.
